"""empty message

Revision ID: 1c9e7d7f7bce
Revises: 229964502879
Create Date: 2024-07-03 18:27:09.586047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c9e7d7f7bce'
down_revision = '229964502879'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sports', sa.String(), nullable=True))
        batch_op.drop_column('aports')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('aports', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('sports')

    # ### end Alembic commands ###
