"""empty message

Revision ID: 229964502879
Revises: 
Create Date: 2024-07-03 18:08:34.283456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '229964502879'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('food_and_Grocery', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('mobilePhones_and_Tablets', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('electronics', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('aports', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('home_Furniture_and_Appliances', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('fashion', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('health_and_Beauty', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('toys', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('toys')
        batch_op.drop_column('health_and_Beauty')
        batch_op.drop_column('fashion')
        batch_op.drop_column('home_Furniture_and_Appliances')
        batch_op.drop_column('aports')
        batch_op.drop_column('electronics')
        batch_op.drop_column('mobilePhones_and_Tablets')
        batch_op.drop_column('food_and_Grocery')

    # ### end Alembic commands ###
